apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
  namespace: apps
spec:
  containers:
    # This could be any image that we can SSH into and has curl.
  - image: radial/busyboxplus:curl
    imagePullPolicy: IfNotPresent
    name: curl
    resources: {}
    stdin: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
    
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: seq
  name: seq
  namespace: tdg
spec:
  containers:
    # This could be any image that we can SSH into and has curl.
    - image: rdatalust/seq
      imagePullPolicy: IfNotPresent
      name: seq
      ports:
        - containerPort: 80
          protocol: TCP
          name: seq-ui
      resources: {}